- name: create data_root directory
  hosts: addworkers
  shell:
    cmd: "mkdir -p {{ data_root }}/common/01-etc-hosts"
    bash: /bin/bash

- name: copy 01-etc-hosts
  hosts: addworkers
  copy:
    src: install-k8s-yamls/common/01-etc-hosts
    dest: "{{ data_root }}/common/01-etc-hosts"

- name: run set-etc-hosts.sh
  hosts: addworkers
  shell:
    cmd: /bin/bash set-etc-hosts.sh
    bash: /bin/bash
    chdir: "{{ data_root }}/common/01-etc-hosts"

- name: set timezone shanghai
  hosts: addworkers
  shell:
    cmd: timedatectl set-timezone Asia/Shanghai
    bash: /bin/bash

- name: set worker node hostname
  hosts: addworkers
  shell:
    cmd: hostnamectl set-hostname {{ hostname }}
    bash: /bin/bash

