- name: create 02-set-local-repo directory
  hosts: allnode
  shell:
    cmd: "mkdir -p {{ data_root }}/common/02-set-local-repo"
    bash: /bin/bash

- name: copy set-os-repo
  hosts: allnode
  copy:
    src: install-k8s-yamls/common/02-set-local-repo
    dest: "{{ data_root }}/common/02-set-local-repo"

- name: run set-os-repo.sh
  hosts: allnode
  shell:
    cmd: /bin/bash set-os-repo.sh
    bash: /bin/bash
    chdir: "{{ data_root }}/common/02-set-local-repo"
