- name: copy 02-install-containerd
  hosts: allnode
  copy:
    src: install-k8s-yamls/master/02-install-containerd
    dest: "{{ data_root }}/master/02-install-containerd"

- name: install containerd
  hosts: allnode
  shell:
    cmd: /bin/bash install-containerd.sh
    chdir: "{{ data_root }}/master/02-install-containerd"
    bash: /bin/bash
